language: ruby
rbenv:
- 2.7.2
addons:
  postgresql: 9.6
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: mOlJW3n4hiIZGfnynx4p7imy9Vu71bKcutnxY8LwWQOLDhs12IRon9QPmRYgij+xNN674OmE/IgKSHdwXo28c0N0Hh1GtmIci1prQYZf4xX8kwXMopeTdIuoDwpYmKkrLLqu9h7MfMX2zMglvblCZOGkVMBwjF1B84SuEHR1DNFKOo+o/LJOi8CqAc8FN/rQ1IfdJ7XOePXGocM51ctpqPortnliEx0Mf2NK/Mm7jSUeBbyFf9X9FIX7/7ZkB/sIdVJ54CiHxMm6y1jnAgxsU/WPSPkaH2oflscTzYk7hhvyy9MCRb0puvZdzQs6dYy4Is86/Onoo1fM0XMpSbTH62NxWIjR1uQcyg3y/45lbIx18MieRomLZ9vlmxXlKPexFdzVkZYTwHD1lXLwlmoSwg4WIMwIMS5rwrKDJLkrrW/duHZcZS8Ft7gp2/sre3Q8wvzsONaPGx5NtUVpGV0fgF3G3/SVUMRbEBySMSFSveCS6/NXGXqdALY8nrpYfH4o1YD9Sr8pvD3FhZO07EXy7UayRmypQXl4LZ34F55r3d+PhjbYyB9KJmtH7oiMDnWmNlIa/Mlf5qz5qkm5xzVSPmES4R41X6Gpn88iaUdme2P9dJ68kB4uPFCArKakRE9j44fCOw1s/SB7wz1L9NWHk6/PeCaOqLqVjuQMTS9IHQM=
  app: shrouded-river-95035
  on:
    repo: aliyamerali/viewing_party
    branch: main
  skip_cleanup: 'true'
