language: ruby
rbenv:
- 2.7.2
addons:
  postgresql: 9.6
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: mSbQd40slHTsU3VMNeN5olljRN5MhYXD20yO+WOsGy69TQ524os4gPs0eZvCJoGPKlNtR6JIvacj0/lOg88UJh2RaNXfS81Tf2amYakg1zMQc5i9cchUPWmb7NRHTeWGHH0IHO4PLcQzjQtqbak/maBhgzGxcGwsIAkbQeh1jD0qwbBlJNrP2JYdTJ8vTc7SNrzQ7gPMKf5etWbevvnofUt34CN5T0K5Z+UKya0Y4/SJEviOFWEv8xxQLevp4Yz6nsrfA0dLjc3bRjDrGMgE4igs6sHgBf1WzdYvj1/Ovey+77qtjkMNbaAyid6g7G4ntOeLAYpJEzXHIqsfRR6SIBqlGIPg5ims2V1xk5wYxrTVFZCDzQCindnNf/JaktubutMg1/SQKJIE1hH5ql56bw3Vuhs+FumSaH4KqONoa5/sqh2iDYOUJrk9M1YvmukHExjYwzB1iNH8LwxQNgEUhfebe3whual7YxKw4QnBjOWnUjqtwhAPINIXlk5p8SqXNOTjtk1EJhI4QfVlRzBKd7bKZ06CiuGLfDKR/om+fU7Rek8UexmoE6TF+jy7X2QkA1AVvyN+Iu3VlOu5ZhgUHHsghdR2bjLdV/XI3PFufKWYnL3zO1EJix7LC1qXx6LmsxYfw6KZKUIun31SS//iYgB8RcYq9S3tTi6os4BfA80=
  app: glacial-scrubland-24016
  on:
    repo: aliyamerali/viewing_party
    branch: am-tinkering
  skip_cleanup: 'true'
env:
  secure: MD5HC4vgY3y74tiRawntac1lkiKsaJHFLP/PSbTtdtwCy7mbFouA4PAAHi+M9hkT+PLAMoJqJban5UTqhIrh/tSYgb6sU4hZmJbgUNIogbMc63RYBkqCUDhZnlCetEGtSYR/PvU9NGGsUP45bdnfu8EFjTJ69gAD8Zjp2NdZQmw9/DSg0JqxrxX860YKFaodE8lXYHL42LibMmXAGqPI0FPTxa7dnXpcqwkiHVHRP3BHgFGewB3RT4sIRbCp3hDnSunonV7IvjfA0S7iFgcyeK6ZUbZgsGlnDN4oXDklHP3Zw43Jc8OFlaDmKQcDoyUG3DWu9ClkP6b+um7gvUxnH2GMIN6J4w+ev7FCN6nUBt7kFzuPleKX5bVCv6uxrOVaiZCa3bn/giXUGBGeMOqZuYfUfYeaghar9oqwNtDISxj1Y4gI71STC8hTGT7xUQ5yGr68MJAd+4G0ue4n8wv0JfhQU8yMczfVlNlw2bTNXBFLJ9WW9tOBgdVwpNlNypZPkLLVhrhzONfsaCBBRMuv9Efi6X6TOH97lzGVhiLt0Pr4FVSwcaFKtU+VWT/4a4U/wIU+JYkM8p/HmeydA0NSCdiZj0mNz7vlxSuMaviacC+3UKZSlTfwdn0T0DhA7xNPRbvZLhzo9IYsmFsqlkJ8dnCLCO90WbS3dzZ0X2Oe/Do=
