language: ruby
rbenv:
- 2.7.2
addons:
  postgresql: 9.6
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key: e0eef0d1-74ca-4b79-9eab-fdec06ed15dc
  app: shrouded-river-95035
  run: rails db:migrate
